### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rds1983** [Xangis/ModernMUD#5]
Hello,
Just wanted to say that I am using this excellent codebase that has so much functionality for my own mud engine: https://github.com/abarim-mud/AbarimMUD
I already did a lot of changes: moved to .Net Core, serialization to json, various refactoring, etc.
I am going to keep the BSD license.

Thanks again!

**Comment by Xangis** [comment]
Very interesting, thank you for letting me know. I wish you the best of success with your project. :)
